name: MokoHub Bounce

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test

      - name: Build Electron app
        run: npm run build

      - name: Package app for distribution
        run: npx electron-builder --dir

      - name: Upload packaged app
        uses: actions/upload-artifact@v4
        with:
          name: MokoHead-App
          path: dist/
